---
- name: Cau hinh tren router
  hosts: all
  gather_facts: no

  tasks:
    - name: Show ip
      cisco.ios.ios_command:
        commands:
          - show ip int brief
      register: output

    - name: Hien thi ket qua
      ansible.builtin.debug:
        var: output.stdout_lines
