---
- name: Lay running-config tu Cisco Router
  hosts: all
  gather_facts: no

  tasks:
    - name: Thu thap cau hinh router
      cisco.ios.ios_facts:
        gather_subset:
          - config

    - name: Hien thi running-config
      ansible.builtin.debug:
        msg: "{{ ansible_net_config.split('\n') }}"
